### PR TITLE
Make Adapt regex more robust

### PR DESCRIPTION
**Pull request by MatthewScholefield**
This allows both newlines in intents and escaped newlines in function definitions where allowed. This fixes issue #18.

### CODE REVIEW

**Comment by MatthewScholefield** [comment]
@lb803 Would you be able to verify this works? If you are on the Mark 1, you can use this script to temporarily install this version without messing with your default version:

```bash
rm -rf /tmp/testvenv
python3 -m venv --without-pip /tmp/testvenv
curl https://bootstrap.pypa.io/get-pip.py | /tmp/testvenv/bin/python
source /tmp/testvenv/bin/activate
pip install git+https://github.com/MycroftAI/mycroft-skills-kit@bugfix/adapt-regex

# In this terminal session, msk now refers to this testing branch:
msk create-test /opt/mycroft/skills/list-manager-skill/
```

**Comment by lb803** [comment]
Thank you @MatthewScholefield  !

Unfortunately, I still get the message 

> MskException: No existing intents found. Please create some first

Is there a log file I can refer to to check what goes wrong? I couldn't find anything useful in /var/log/mycroft/

**Comment by MatthewScholefield** [comment]
@lb803 I just realized my instructions were slightly wrong. Could try running the updated commands? (I forgot to even activate the virtualenv so it should have failed with a permission error rather than installing the new version)

For reference, here are the updated commands posted here as well:
```
rm -rf /tmp/testvenv
python3 -m venv --without-pip /tmp/testvenv
curl https://bootstrap.pypa.io/get-pip.py | /tmp/testvenv/bin/python
source /tmp/testvenv/bin/activate
pip install git+https://github.com/MycroftAI/mycroft-skills-kit@bugfix/adapt-regex

# In this terminal session, msk now refers to this testing branch:
msk create-test /opt/mycroft/skills/list-manager-skill/
```
For me, this is what I get:
```
$ msk create-test /opt/mycroft/skills/list-manager-skill/

Which intent would you like to test?
1. handle_read
2. handle_add
3. handle_del

> 
```

**Comment by lb803** [comment]
Thank you @MatthewScholefield !!
This time it worked like a charm!

**Pull request merged**
